servicea:
  build: ./serviceA
  ports:
    - "8081:8081"
  links:
    - redis
serviceb:
  build: ./serviceB
  ports:
    - "8082:8082"
  links:
    - redis
redis:
  image: redis:latest
  ports:
    - "6379:6379"